version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DEBUG=False
      - MAX_UPLOAD_SIZE=10485760
      - ALLOWED_EXTENSIONS=pdf
      - OCR_ENABLED=True
      - BACKEND_CORS_ORIGINS=
    volumes:
      - ./data:/app/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s